### ISSUE TITLE
Unable to compile the mac app

### ISSUE THREAD

**Issue by AalokParikh** [Shopify/superdb#14]
get the below error

ld: library not found for -lSuperDBCoreMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jbrennan** [comment]
Hmmm. Are you building with the workspace file open? There might be difficulty if you're trying to build the Mac app from its own project, because then it won't be able to find the library it needs (SuperDBCoreMac).

**Comment by AalokParikh** [comment]
Thanks for your quick and spontaneous reply.
No. There isn't any workspace file is open. May that is the problem and sorry for that.
But it gives me more errors when I open workspace file and try to build it.

NOTE :8ball: (Let me inform you that I use github for mac application to clone the repository to my mac)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FSInterpreter", referenced from:
      objc-class-ref in libSuperDBCoreMac.a(SuperInterpreter.o)
  "_OBJC_CLASS_$_Geometry", referenced from:
      objc-class-ref in libSuperDBCoreMac.a(SuperInterpreter.o)
  "_OBJC_CLASS_$_SuperInterpreterObjectBrowser", referenced from:
      objc-class-ref in libSuperDBCoreMac.a(SuperInterpreter.o)
  "_classNames", referenced from:
      ___41-[SuperInterpreter setupResponseHandlers]_block_invoke_095 in libSuperDBCoreMac.a(SuperInterpreter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jbrennan** [comment]
Which version of Xcode are you using? Please make sure you're using the latest version from the App Store.

Failing that, make sure when you clone the repository that you also recursively pull all the submodules in. I haven't used Github-for-Mac, but I bet it can do it somehow. If not, there are instructions on how to do it in the Readme. This will make sure that sub-projects for "Super Debug" are all correctly pulled in.

You should then be able to build the app. Open the "SuperWorkspace.xcworkspace" file, and then from the Scheme dropdown select "Super Debug -> My Mac 64-bit" and hit the Run button.

Let me know if that helps.

**Comment by AalokParikh** [comment]
Just got is solved.
Have to remove all the data related to the superdb and after delete just re-clone it again and the problem is solved :)
Thanks for your valuable time and replies to my problem.
I really appreciate it.

**Comment by jbrennan** [comment]
Glad you got it working!
