### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AalokParikh** [Shopify/superdb#15]
I got two files missing in workspace when I open it.
![Screen Shot 2013-03-02 at 1 00 53 PM](https://f.cloud.github.com/assets/1628260/212545/4cb4e786-830b-11e2-8114-683b995622e0.png)

**Comment by jbrennan** [comment]
Those missing files are a known issue, although I'm not entirely sure what causes it.

I do know, however that they shouldn't actually be causing any trouble with your build. I see them on my machine, as well, but the "Super Debug" target still builds just fine.
