### ISSUE TITLE
crash: range out of bounds

### ISSUE THREAD

**Issue by mikey0000** [Shopify/superdb#19]
I get a crash on the develop branch whenever I try to execute a method that requires text input
it seems to occur only when I use double quotes, also it interprets all symbols in a non ascii format which is very annoying, is there a way to change that? I don't mind helping if someone points me to the right place.

The trace is below

5   Super Debug                         0x000000010b13d485 -[JBShellView showErrorOutput:errorRange:] + 709
6   Super Debug                         0x000000010b1335d2 __47-[SuperDebugAreaWindowController windowDidLoad]_block_invoke69 + 722
7   Super Debug                         0x000000010b160815 -[SuperInterpreterClient dataByProcessingJSTPBodyData:] + 197
8   Super Debug                         0x000000010b142a68 -[SuperJSTP socket:didReadData:withTag:] + 264
9   Super Debug                         0x000000010b159943 __37-[GCDAsyncSocket completeCurrentRead]_block_invoke + 83

**Comment by jbrennan** [comment]
@mikey0000 It seems to be an issue with Mavericks’s auto-curly quote replacement. You should be able to turn that off in Edit -> Substitutions. Failing that, I think #20 should also fix this on the iOS side.

**Comment by mikey0000** [comment]
Thanks, I realised that single quotes work fine, which solved the issue. I’ll try turning off edit substitutions.
