### ISSUE TITLE
Missing JBShellView in mac app

### ISSUE THREAD

**Issue by LukaJankovic** [Shopify/superdb#23]
I tried adding JBShellView manually, however, it required ParseKit, which lead to many more frameworks being manually added. Only to come to the conclusion that it wouldn't work with the SuperDraggableShellView. I tried re-gitting and re-downloading Superdb, but with the same results. I also didn't find any instructions about it.

**Comment by jbrennan** [comment]
Ah, `JBShellView` is a submodule, so you need to fetch all the submodules. From the readme:

```
git submodule update --init --recursive
```

Do that in the superdb directory and it should fetch all the submodules for you. Then you should be able to build.

**Comment by LukaJankovic** [comment]
Thanks for the quick answer @jbrennan, I'm new to git, but it fixed the problem, Thanks!

**Comment by jbrennan** [comment]
You’re welcome. Submodules are a pain in the butt, so don’t sweat it!
