### ISSUE TITLE
Unable to compile mac app

### ISSUE THREAD

**Issue by abecevello** [Shopify/superdb#4]
I am unable to compile the mac app. When compiling "Super Debug" for "My Mac 64-bit" I get a compile error in SuperDraggableShellView.m: 'ParseKit/ParseKit.h' file not found.

Trying to initialize submodules for git on the command line gives an error about a resource unavailable.
~/Documents/Work/XCode/superdb$ git submodule update --init --recursive
/usr/libexec/git-core/git-submodule: fork: Resource temporarily unavailable
No submodule mapping found in .gitmodules for path 'SuperDebug/Super Debug/Libraries/JBShellView'

**Comment by jbrennan** [comment]
Hmmm, I'll look into that. Thanks Adam!

**Comment by jbrennan** [comment]
I'm not really sure what the issue was, but the readme has been updated a bit so that should help.
